# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDKQAiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKQAiOS
  pod 'MediastreamPlatformSDKxC', '~> 3.0.0-alpha.09'

end
